name: smartmart_dbt_project
version: '1.0'
config-version: 2
 
profile: smartmart_profile   # ensure a matching profile exists in your profiles.yml
 
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
 
models:
  smartmart_dbt_project:
    staging:
      +materialized: view
    marts:
      +materialized: incremental
    dims:
      +materialized: table
